version: "3.7"

services:
    app:
        build: .
        container_name: family_feud_app
        working_dir: /usr/local/apache2/htdocs/
        ports:
            - 8000:80
        volumes:
            - type: bind
              source: ./
              target: /usr/local/apache2/htdocs/